spring.application.name=api-donnees
server.port=8090

# Swagger derrière le proxy Codespaces
server.forward-headers-strategy=framework
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.operationsSorter=method
spring.mvc.problemdetails.enabled=true

# Authentification (formation : valeurs connues de tous)
donnees.cle-api=cle-demo-etl-2026
donnees.jwt.secret=cle-signature-api-donnees-formation-2026-32o!
